server:
  contextPath: /homeaccountance
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testData
    username: sa
    password:
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    url: jdbc:h2:mem:testData
    user: sa
    password: